USE [master]
GO
/****** Object:  Database [myadmindb]    Script Date: 22/08/2019 17:01:32 ******/
CREATE DATABASE [myadmindb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'myadmindb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\myadmindb.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'myadmindb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\myadmindb_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [myadmindb] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [myadmindb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [myadmindb] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [myadmindb] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [myadmindb] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [myadmindb] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [myadmindb] SET ARITHABORT OFF 
GO
ALTER DATABASE [myadmindb] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [myadmindb] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [myadmindb] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [myadmindb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [myadmindb] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [myadmindb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [myadmindb] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [myadmindb] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [myadmindb] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [myadmindb] SET  DISABLE_BROKER 
GO
ALTER DATABASE [myadmindb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [myadmindb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [myadmindb] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [myadmindb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [myadmindb] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [myadmindb] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [myadmindb] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [myadmindb] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [myadmindb] SET  MULTI_USER 
GO
ALTER DATABASE [myadmindb] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [myadmindb] SET DB_CHAINING OFF 
GO
ALTER DATABASE [myadmindb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [myadmindb] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [myadmindb] SET DELAYED_DURABILITY = DISABLED 
GO
USE [myadmindb]
GO
/****** Object:  User [root]    Script Date: 22/08/2019 17:01:32 ******/
CREATE USER [root] FOR LOGIN [root] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_owner] ADD MEMBER [root]
GO
ALTER ROLE [db_accessadmin] ADD MEMBER [root]
GO
ALTER ROLE [db_securityadmin] ADD MEMBER [root]
GO
ALTER ROLE [db_ddladmin] ADD MEMBER [root]
GO
ALTER ROLE [db_backupoperator] ADD MEMBER [root]
GO
ALTER ROLE [db_datareader] ADD MEMBER [root]
GO
ALTER ROLE [db_datawriter] ADD MEMBER [root]
GO
ALTER ROLE [db_denydatareader] ADD MEMBER [root]
GO
ALTER ROLE [db_denydatawriter] ADD MEMBER [root]
GO
/****** Object:  Table [dbo].[USUARIO]    Script Date: 22/08/2019 17:01:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[USUARIO](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[nome] [varchar](200) NOT NULL,
	[sobrenome] [varchar](255) NOT NULL,
	[email] [varchar](255) NOT NULL,
	[senha] [varchar](255) NOT NULL,
	[token] [varchar](255) NULL,
	[data_expiracao_token] [datetime] NULL,
	[ativo] [char](1) NULL,
	[data_ultimo_acesso] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
USE [master]
GO
ALTER DATABASE [myadmindb] SET  READ_WRITE 
GO
