//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myadmin.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public int id { get; set; }
        public string nome { get; set; }
        public string sobrenome { get; set; }
        public string email { get; set; }
        public string senha { get; set; }
        public string token { get; set; }
        public Nullable<System.DateTime> data_expiracao_token { get; set; }
        public string ativo { get; set; }
        public Nullable<System.DateTime> data_ultimo_acesso { get; set; }
    }
}
